spring.application.name=booking-service
server.port=8088

# PostgreSQL - booking_db
spring.datasource.url=jdbc:postgresql://localhost:5432/booking_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=shreenivasa

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8762/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true